### ISSUE TITLE
Include an example config.ini

### ISSUE THREAD

**Issue by jason-murray** [codeworkx/ginlong-mqtt#2]
There is no config.ini sample in the repo, and this file seems to be required to start the script.

**Comment by jason-murray** [comment]
What I ended up with based on https://github.com/dpoulson/ginlong-mqtt and error messages.

```
[DEFAULT]
listen_address = 0.0.0.0
listen_port = 10000

[MQTT]
client_id = ginlong
mqtt_server = localhost
mqtt_port = 1883
client_pw = secret
```

**Comment by codeworkx** [comment]
thanks, done.
